### ISSUE TITLE
Same origin policy error

### ISSUE THREAD

**Issue by sashans13** [sole/gifwall#2]
Hi guys, here's the problem:
Whenever I open index.html in chrome (I downloaded the zip, extracted), I don't get the camera prompt and after the timeout I get the sad error message. If I enable cross origin policy, then I get it to work. No problem in firefox whatsoever. I've tried grepping the code for outer links, but they're all commented, so it shouldn't be a problem. Any ideas why this happens?
Mac OS X 10.10.5
Chrome Version 45.0.2454.99 (64-bit)

**Comment by sole** [comment]
This might be because Chrome has changed the security requirements and won't allow accessing the camera using a file:/// protocol.
I suggest you try to upload the files somewhere, or use a local server and then access the files via that. Here's one way to do it: http://soledadpenades.com/2014/07/12/lute/

PS Also as it happens there's no "guy" here, so please be considerate and try addressing people with a less gendered greeting :-)

**Comment by sashans13** [comment]
Wow, I apologise for the "guys" bit, duly noted :)

Yup, the issue is no more, thank you.
